services:
  devtools:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devtools
    ports:
      - "8080:8080" 
    volumes:
      - ./dist:/app/dist
    restart: unless-stopped

